### ISSUE TITLE
Problem using list of freq in synthdef

### ISSUE THREAD

**Issue by d3vp** [smrg-lm/sc3#13]
Hi,

First of all, thank you for the great library. I am trying to implement [this example](https://en.wikibooks.org/wiki/Designing_Sound_in_SuperCollider/DTMF) using sc3.

```python
from sc3.all import *

@synthdef
def dtmf(freq=(770, 1633), out=0, amp=0.2, gate=1):
    son = SinOsc.ar(freq, 0).sum() * amp
    env = EnvGen.ar(Env.asr(0.001, 1, 0.001), gate, done_action=2)
    Out.ar(out, Pan2.ar(son * env * amp))

Pbind({'instrument': 'dtmf',
        'dur': Pwhite(0.2, 0.5),
        'sustain': 0.15,
        'amp': 0.3,
        'freq': Prand([[697, 1209],[770, 1209], [852, 1209], [697, 1336]], 13)
}).play();
```

But getting following error:
```
ERROR:sc3.base.clock:EventStreamPlayer(EventStreamPlayer._stream_player_func.<locals>.esp_func) scheduled on SystemClock
Traceback (most recent call last):
  File "/Supercollider/sc3/sc3/base/clock.py", line 237, in _run
    delta = task.__awake__(cls)
  File "/Supercollider/sc3/sc3/base/stream.py", line 608, in __awake__
    return self.next((self, clock))
  File "/Supercollider/sc3/sc3/base/stream.py", line 491, in next
    self._last_value = next(self._iterator)
  File "/Supercollider/sc3/sc3/seq/eventstream.py", line 140, in esp_func
    yield self._play_and_delta(outevent)
  File "/Supercollider/sc3/sc3/seq/eventstream.py", line 148, in _play_and_delta
    outevent.play()
  File "/Supercollider/sc3/sc3/seq/event.py", line 624, in play
    self['freq'] = self._detuned_freq()  # Before _get_msg_params.
  File "/Supercollider/sc3/sc3/seq/event.py", line 221, in _detuned_freq
    return self('freq') * self('harmonic') + self('detune')
TypeError: can't multiply sequence by non-int of type 'float'
```

Not sure if I am doing something wrong or it is a bug or missing feature.

**Comment by smrg-lm** [comment]
Hi

Thanks for the report. Currently, patterns don't support multichannel expansion or point wise operations over arrays. I see this case is special because it is a synthdef's arrayed control. I will have to take a look at this, it requires some considerations.

By now, operations over value streams are Python operations over Python types, that was on purpose.

```python
# This will not work because factor is float, e.g. [1, 2, 3] * 0.5
p = Prand([[1, 2],[3, 4]], 3) * 0.5  # float
q = stream(p)
list(q)

# With an int it will work but '*' in Python extends the list
p = Prand([[1, 2],[3, 4]], 3) * 2  # int
q = stream(p)
list(q)
```

In the second case each next call returns a list, e.g. [1, 2] that is "multiplied" by 2 and produces [1, 2, 1, 2], etc. The only way to do it by now is to make the routine explicitly or to use two synths with Ppar.

```python
@routine
def p():
    dur = Pwhite(0.2, 0.5)
    legato = 0.15
    amp = 0.3
    freq = Prand([(697, 1209),(770, 1209), (852, 1209), (697, 1336)], 13)

    for d, f in zip(dur, freq):
        synth = dtmf(freq=f, amp=amp)
        yield d * legato
        synth.release()
        yield d - (d * legato)

p.play()
```

I know this is not optimal. I will look at it.

**Comment by d3vp** [comment]
Thanks for the quick and detailed reply. I like the idea of using Python instead of sclang. I have actually forked this repo and I am going to add missing things like methods, as I encounter them. So far, I only added 2 new methods.

As I suspected, this issue does indeed require some thinking and I have not seen code in too much detail. So, I am unable to think about larger design issues. For now, I will use the workaround.

**Comment by smrg-lm** [comment]
If you tell me which methods are missing I can tell you if it was intended or not, we can discuss it in the discussions tab.

**Comment by smrg-lm** [comment]
This issue should be fixed now, I still have to do the tests. Note that for arrayed controls you need to use tuples instead of lists and event's inner conversions will work. List would be multichannel expansion but that isn't implemented for events.

```python
from sc3.all import *

s.boot()

@synthdef
def dtmf(freq=(770, 1633), out=0, amp=0.2, gate=1):
    son = SinOsc.ar(freq, 0).sum() * amp
    env = EnvGen.ar(Env.asr(0.001, 1, 0.001), gate, done_action=2)
    Out.ar(out, Pan2.ar(son * env * amp))


p = Pbind({
    'instrument': 'dtmf',
    'dur': Pwhite(0.2, 0.5),
    'sustain': 0.15,
    'amp': 0.3,
    'freq': Prand([(697, 1209), (770, 1209), (852, 1209), (697, 1336)], 13)
})

p.trace().play()
```
